/*
 * generated by Xtext 2.25.0
 */
package robLANG_ASOS.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class RobLANGAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("robLANG_ASOS/parser/antlr/internal/InternalRobLANG.tokens");
	}
}
