/*
 * generated by Xtext 2.25.0
 */
package robLANG_ASOS.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import robLANG_ASOS.parser.antlr.internal.InternalRobLANGParser;
import robLANG_ASOS.services.RobLANGGrammarAccess;

public class RobLANGParser extends AbstractAntlrParser {

	@Inject
	private RobLANGGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalRobLANGParser createParser(XtextTokenStream stream) {
		return new InternalRobLANGParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Robot";
	}

	public RobLANGGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(RobLANGGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
