/*
 * generated by Xtext 2.25.0
 */
package robLANG_ASOS.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractRobLANGScopeProvider extends DelegatingScopeProvider {
}
